### ISSUE TITLE
Remove hardcoded paths

### ISSUE THREAD

**Issue by mustafacc** [SiEPIC/SiEPIC_Analysis#5]
these only work on your PC. these should be added to python system path
https://github.com/Trufflechoco/SiEPIC_Analysis/blob/d53ca6444ae6adc1c14ee0b52f272ed2718b19ad/analysis_packageV2/device.py#L2

This should be a relative path
https://github.com/Trufflechoco/SiEPIC_Analysis/blob/d53ca6444ae6adc1c14ee0b52f272ed2718b19ad/main.py#L5

**Comment by Trufflechoco** [comment]
But I wouldn't know where the user has stored the downloaded package? And for the second issue, I wouldn't know where the user has stored the data?

**Comment by mustafacc** [comment]
1st: the package should be pip installable therefore added to the python's site packages by default

2nd: you can leave it as is for now
